In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

In [2]:
pca_flat = pd.read_csv('C:/Users/TheSteubenator/Documents/Python Project 522/pca_selfies.csv')

In [3]:
X=pca_flat.drop(['position','label'],axis=1)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [4]:
param_grid = {'C': [1, 10,100], 'gamma': [1,0.1,0.001], 'kernel': ['rbf']} 
grid_rbf = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_rbf.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] 

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=100, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV]  C=100, gamma=0.001, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV]  C=100, gamma=0.001, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ..................................
[CV]  C=100, gamma=0.001, kernel=rbf, score=0.3333333333333333, total=   0.0s


[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    0.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1, 10, 100], 'gamma': [1, 0.1, 0.001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [6]:
grid_rbf.best_score_

0.3333333333333333

In [7]:
from sklearn.metrics import classification_report,confusion_matrix
pred_rbf = grid_rbf.predict(X_test)
print(confusion_matrix(y_test,pred_rbf))
print(classification_report(y_test,pred_rbf))

[[ 0  0 16]
 [ 0  0 16]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        16
           2       0.00      0.00      0.00        16
           3       0.33      1.00      0.50        16

   micro avg       0.33      0.33      0.33        48
   macro avg       0.11      0.33      0.17        48
weighted avg       0.11      0.33      0.17        48



## Scaled Models

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=pca_flat.drop(['position','label'],axis=1)
X = scaler.fit_transform(X)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [22]:
print(X_test_s.shape)

(48, 163)


In [9]:
param_grid = {'C': [1, 10,100], 'gamma': [1,0.1,0.001], 'kernel': ['rbf']} 
grid_rbf = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_rbf.fit(X_train_s,y_train_s)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.35714285714285715, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.4523809523809524, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.38461538461538464, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.358974358974359, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV]

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    0.1s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1, 10, 100], 'gamma': [1, 0.1, 0.001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [10]:
grid_rbf.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

In [11]:
grid_rbf.best_score_

0.8833333333333333

In [12]:
from sklearn.metrics import classification_report,confusion_matrix
pred_rbf = grid_rbf.predict(X_test_s)
print(confusion_matrix(y_test_s,pred_rbf))
print(classification_report(y_test_s,pred_rbf))

[[16  0  0]
 [ 0 15  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      0.94      0.97        16
           3       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



In [24]:
param_grid = {'C': [0.00001,0.0001,0.001,0.01,0.1,1], 'coef0': [0.0001,0.001,0.01,0.1,0.5,1,1.5,2,2.5,3,10], 'degree': [1,2,3,4,5,6,7,8,9,10], 'kernel': ['poly']}
grid_poly = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_poly.fit(X_train_s,y_train_s)

Fitting 3 folds for each of 660 candidates, totalling 1980 fits
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.38461

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=1e-05, coef0=0.001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.38461538461538464, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=3, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=3, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=3, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=3, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001,

[CV]  C=1e-05, coef0=0.1, degree=3, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=3, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=3, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=5, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=5, kerne

[CV]  C=1e-05, coef0=1, degree=5, kernel=poly, score=0.5897435897435898, total=   0.0s
[CV] C=1e-05, coef0=1, degree=5, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=5, kernel=poly, score=0.6410256410256411, total=   0.0s
[CV] C=1e-05, coef0=1, degree=6, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=6, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=1, degree=6, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=1, degree=6, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=1, degree=7, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=7, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=1, degree=7, kernel=poly .........................
[CV]  C=1e-05, coef0=1, degree=7, kernel=poly, score

[CV]  C=1e-05, coef0=2, degree=7, kernel=poly, score=0.6923076923076923, total=   0.0s
[CV] C=1e-05, coef0=2, degree=8, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=8, kernel=poly, score=0.5714285714285714, total=   0.0s
[CV] C=1e-05, coef0=2, degree=8, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=8, kernel=poly, score=0.5384615384615384, total=   0.0s
[CV] C=1e-05, coef0=2, degree=8, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=8, kernel=poly, score=0.6153846153846154, total=   0.0s
[CV] C=1e-05, coef0=2, degree=9, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=9, kernel=poly, score=0.42857142857142855, total=   0.0s
[CV] C=1e-05, coef0=2, degree=9, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=2, degree=9, kernel=poly .........................
[CV]  C=1e-05, coef0=2, degree=9, kernel=poly, score

[CV]  C=1e-05, coef0=3, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=3, degree=10, kernel=poly ........................
[CV]  C=1e-05, coef0=3, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=10, degree=1, kernel=poly ........................
[CV]  C=1e-05, coef0=10, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=1e-05, coef0=10, degree=1, kernel=poly ........................
[CV]  C=1e-05, coef0=10, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=10, degree=1, kernel=poly ........................
[CV]  C=1e-05, coef0=10, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=10, degree=2, kernel=poly ........................
[CV]  C=1e-05, coef0=10, degree=2, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=1e-05, coef0=10, degree=2, kernel=poly ........................
[CV]  C=1e-05, coef0=10, degree=2, kernel=poly, score=0.8717948

[CV]  C=0.0001, coef0=0.001, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=3, kernel=poly ....................
[CV]  C=0.0001, coef0=0.001, degree=3, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=4, kernel=poly ....................
[CV]  C=0.0001, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=4, kernel=poly ....................
[CV]  C=0.0001, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=4, kernel=poly ....................
[CV]  C=0.0001, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=5, kernel=poly ....................
[CV]  C=0.0001, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.001, degree=5, kernel=poly ....................
[CV]  C=0.0001, coef0=0

[CV]  C=0.0001, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=6, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=6, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=6, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=7, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=7, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.1, degree=7, kernel=poly ......................
[CV]  C=0.0001, coef0=0.1, degree=

[CV]  C=0.0001, coef0=1, degree=7, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=1, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=8, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.0001, coef0=1, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=8, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=1, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=1, degree=9, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=9, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.0001, coef0=1, degree=9, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=1, degree=9, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=9, kernel=poly,

[CV]  C=0.0001, coef0=2, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.0001, coef0=2, degree=10, kernel=poly .......................
[CV]  C=0.0001, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=2, degree=10, kernel=poly .......................
[CV]  C=0.0001, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.0001, coef0=2.5, degree=1, kernel=poly ......................
[CV]  C=0.0001, coef0=2.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.0001, coef0=2.5, degree=1, kernel=poly ......................
[CV]  C=0.0001, coef0=2.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=2.5, degree=1, kernel=poly ......................
[CV]  C=0.0001, coef0=2.5, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.0001, coef0=2.5, degree=2, kernel=poly ......................
[CV]  C=0.0001, coef0=2.5, degree=2, kernel=poly, sco

[CV]  C=0.0001, coef0=10, degree=2, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=10, degree=2, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=2, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.0001, coef0=10, degree=3, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=3, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=0.0001, coef0=10, degree=3, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=3, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=10, degree=3, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=3, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.0001, coef0=10, degree=4, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=4, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.0001, coef0=10, degree=4, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=4, kern

[CV]  C=0.001, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=4, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=5, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=5, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=5, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=6, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=6, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, 

[CV]  C=0.001, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=7, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=7, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.1, degree=9, kernel=poly .......................
[CV]  C=0.001, coef0=0.1, degree=9, kern

[CV]  C=0.001, coef0=1, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=1, degree=10, kernel=poly ........................
[CV]  C=0.001, coef0=1, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.001, coef0=1, degree=10, kernel=poly ........................
[CV]  C=0.001, coef0=1, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=1, degree=10, kernel=poly ........................
[CV]  C=0.001, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=1, kernel=poly, score=0.923

[CV]  C=0.001, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=1, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=2, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=2, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=2, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=2, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.001, coef0=2.5, degree=2, kernel=poly .......................
[CV]  C=0.001, coef0=2.5, degree=2, kernel=poly, score=0.

[CV]  C=0.001, coef0=3, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=10, degree=1, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.001, coef0=10, degree=1, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.001, coef0=10, degree=1, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.001, coef0=10, degree=2, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=2, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=0.001, coef0=10, degree=2, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=2, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.001, coef0=10, degree=2, kernel=poly ........................
[CV]  C=0.001, coef0=10, degree=2, kernel=poly, score=0.897435

[CV]  C=0.01, coef0=0.001, degree=2, kernel=poly, score=0.38461538461538464, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=3, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree=3, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=3, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=3, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree=3, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=4, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=4, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.001, degree=4, kernel=poly ......................
[CV]  C=0.01, coef0=0.001, degree

[CV]  C=0.01, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=5, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=5, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=6, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=6, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=6, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=7, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=7, kernel=poly

[CV]  C=0.01, coef0=1, degree=7, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=1, degree=7, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=7, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=1, degree=8, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=8, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=1, degree=8, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=8, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=1, degree=8, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=1, degree=9, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=9, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=1, degree=9, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=9, kernel=poly, score=0.33333

[CV]  C=0.01, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2, degree=9, kernel=poly ..........................
[CV]  C=0.01, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2.5, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=2.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.01, coef0=2.5, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=2.5, degree=1, kernel=poly, score=0.871794871794871

[CV]  C=0.01, coef0=10, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.01, coef0=10, degree=1, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.01, coef0=10, degree=2, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=2, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=0.01, coef0=10, degree=2, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=2, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.01, coef0=10, degree=2, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=2, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.01, coef0=10, degree=3, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=3, kernel=poly, score=0.8571428571428571, total=   0.0s
[CV] C=0.01, coef0=10, degree=3, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=3, kernel=poly, score

[CV]  C=0.1, coef0=0.001, degree=3, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=3, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=3, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=3, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=4, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=4, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=4, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=5, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=5, kern

[CV]  C=0.1, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=5, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=6, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=6, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=6, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=7, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.1, degree=7, kernel=poly .........................
[CV]  C=0.1, coef0=0.1, degree=7, kernel=poly, score

[CV]  C=0.1, coef0=1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=1, degree=8, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=8, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=1, degree=8, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=1, degree=8, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=1, degree=9, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=9, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=1, degree=9, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=1, degree=9, kernel=poly ...........................
[CV]  C=0.1, coef0=1, degree=9, kernel=poly, score=0.333333333

[CV]  C=0.1, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=2, degree=10, kernel=poly ..........................
[CV]  C=0.1, coef0=2, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=2, degree=10, kernel=poly ..........................
[CV]  C=0.1, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=2, degree=10, kernel=poly ..........................
[CV]  C=0.1, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=2.5, degree=1, kernel=poly .........................
[CV]  C=0.1, coef0=2.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.1, coef0=2.5, degree=1, kernel=poly .........................
[CV]  C=0.1, coef0=2.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.1, coef0=2.5, degree=1, kernel=poly .........................
[CV]  C=0.1, coef0=2.5, degree=1, kernel=poly, score=0.9230769230769231, t

[CV]  C=0.1, coef0=10, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.1, coef0=10, degree=2, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=2, kernel=poly, score=0.8809523809523809, total=   0.0s
[CV] C=0.1, coef0=10, degree=2, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=2, kernel=poly, score=0.8461538461538461, total=   0.0s
[CV] C=0.1, coef0=10, degree=2, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=2, kernel=poly, score=0.7948717948717948, total=   0.0s
[CV] C=0.1, coef0=10, degree=3, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=3, kernel=poly, score=0.8571428571428571, total=   0.0s
[CV] C=0.1, coef0=10, degree=3, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=3, kernel=poly, score=0.8461538461538461, total=   0.0s
[CV] C=0.1, coef0=10, degree=3, kernel=poly ..........................
[CV]  C=0.1, coef0=10, degree=3, kernel=poly, score=0.7692

[CV]  C=1, coef0=0.001, degree=3, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.001, degree=4, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=4, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1, coef0=0.001, degree=4, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=4, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=0.001, degree=4, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.001, degree=5, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.001, degree=5, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.001, degree=5, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=5, kernel=poly, score

[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=7, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=7, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=7, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=8, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=8, kernel=poly, score=0.33333333333

[CV]  C=1, coef0=1, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=8, kernel=poly .............................
[CV]  C=1, coef0=1, degree=8, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1, coef0=1, degree=8, kernel=poly .............................
[CV]  C=1, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=8, kernel=poly .............................
[CV]  C=1, coef0=1, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=9, kernel=poly .............................
[CV]  C=1, coef0=1, degree=9, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1, coef0=1, degree=9, kernel=poly .............................
[CV]  C=1, coef0=1, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=9, kernel=poly .............................
[CV]  C=1, coef0=1, degree=9, kernel=poly, score=0.3333333333333333, total

[CV]  C=1, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=2, degree=9, kernel=poly .............................
[CV]  C=1, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=2, degree=10, kernel=poly ............................
[CV]  C=1, coef0=2, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1, coef0=2, degree=10, kernel=poly ............................
[CV]  C=1, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=2, degree=10, kernel=poly ............................
[CV]  C=1, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=2.5, degree=1, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=1, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=1, coef0=2.5, degree=1, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=1, kernel=poly, score=0.9230769230769231, tot

[CV]  C=1, coef0=10, degree=1, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=1, coef0=10, degree=2, kernel=poly ............................
[CV]  C=1, coef0=10, degree=2, kernel=poly, score=0.8809523809523809, total=   0.0s
[CV] C=1, coef0=10, degree=2, kernel=poly ............................
[CV]  C=1, coef0=10, degree=2, kernel=poly, score=0.8461538461538461, total=   0.0s
[CV] C=1, coef0=10, degree=2, kernel=poly ............................
[CV]  C=1, coef0=10, degree=2, kernel=poly, score=0.8205128205128205, total=   0.0s
[CV] C=1, coef0=10, degree=3, kernel=poly ............................
[CV]  C=1, coef0=10, degree=3, kernel=poly, score=0.8571428571428571, total=   0.0s
[CV] C=1, coef0=10, degree=3, kernel=poly ............................
[CV]  C=1, coef0=10, degree=3, kernel=poly, score=0.8461538461538461, total=   0.0s
[CV] C=1, coef0=10, degree=3, kernel=poly ............................
[CV]  C=1, coef0=10, degree=3, kernel=poly, score=0.7692307692307693, 

[Parallel(n_jobs=1)]: Done 1980 out of 1980 | elapsed:   11.1s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1], 'coef0': [0.0001, 0.001, 0.01, 0.1, 0.5, 1, 1.5, 2, 2.5, 3, 10], 'degree': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'kernel': ['poly']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [25]:
grid_poly.best_params_

{'C': 1e-05, 'coef0': 1, 'degree': 2, 'kernel': 'poly'}

In [20]:
grid_poly.best_score_

0.9416666666666667

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
pred_poly = grid_poly.predict(X_test_s)
print(confusion_matrix(y_test_s,pred_poly))
print(classification_report(y_test_s,pred_poly))

[[15  1  0]
 [ 0 16  0]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        16
           3       1.00      1.00      1.00        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48

