# Facial Recognition #

Imports

In [1]:
from skimage.io import imread_collection
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import warnings
warnings.filterwarnings("ignore")

## Reading in the Data

### formating the images

In [2]:
def flat_images(path,label):
#this function reads in images and then flattens them into a dataframe
    images=imread_collection(path)
    flat_images=[]
    for i in range(len(images)):
        img=images[i]
        img1=img.flatten()
        flat_images.append(img1)
    length=flat_images[1].shape
    df=pd.DataFrame(flat_images)
    df['label']=label
    return(df)

In [3]:
#specifies path and label for pictures of Austin
path = 'C:/Users/sam2146/Documents/522_Proj/small/*.jpg'
label=[1,2,3]
df=flat_images(path,label[0])

In [4]:
#Adds a position label so we can tell what features are in the pictures
position=[np.floor(i/7) for i in df.index]
df['position']=position

In [5]:
df.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  254  255  255  254  255  255  254  255  255  ...     207     201   
1  223  213  204  225  215  206  225  215  206  224  ...      82      94   
2  223  213  204  222  212  203  221  211  202  222  ...      65      77   
3  223  213  204  223  213  204  224  214  205  225  ...      66      77   
4  218  208  198  222  212  202  223  213  203  223  ...      71      86   
5  219  209  200  222  212  203  226  216  207  225  ...      71      79   
6  219  206  197  223  210  201  222  209  200  220  ...      59      74   
7  225  216  207  225  216  207  225  216  207  224  ...      40      51   
8  223  214  209  223  214  209  224  215  210  222  ...     228     226   
9  221  212  205  221  212  205  223  214  207  223  ...     229     226   

   307194  307195  307196  307197  307198  307199  label  position  
0     213     208     202     213     208     202      1       0.0  
1      90      90     100      92      92     102      1       0.0  
2      63      65      77      63      65      77      1       0.0  
3      60      58      71      60      58      72      1       0.0  
4      75      74      92      73      72      90      1       0.0  
5      73      71      85      76      73      94      1       0.0  
6      49      52      69      65      68      87      1       0.0  
7      37      35      46      38      36      47      1       1.0  
8     236     228     226     236     228     226      1       1.0  
9     237     229     226     238     230     227      1       1.0  

[10 rows x 307202 columns]

In [6]:
#Path and labels for Tyler
path = 'C:/Users/sam2146/Documents/522_Proj/Tyler/*.jpg'
label=[1,2,3]
df_t=flat_images(path,label[1])

In [7]:
position=[np.floor(i/7) for i in df_t.index]
df_t['position']=position

In [8]:
df_t.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  246  241  235  248  243  237  250  245  239  250  ...     215     212   
1  255  253  246  255  253  246  255  253  246  255  ...     215     211   
2  243  233  231  243  233  231  243  233  231  244  ...     209     204   
3  243  233  231  244  234  232  244  234  232  244  ...     212     207   
4  248  238  229  249  239  230  250  240  231  249  ...     215     206   
5  248  238  229  249  239  230  249  239  230  247  ...     216     206   
6  243  234  229  243  234  229  243  234  229  243  ...     211     206   
7  251  243  240  251  243  240  251  243  240  251  ...     217     214   
8  247  238  231  248  239  232  248  239  232  247  ...     218     215   
9  252  245  239  250  243  237  250  243  237  252  ...     215     211   

   307194  307195  307196  307197  307198  307199  label  position  
0     223     215     212     225     217     214      2       0.0  
1     223     212     208     223     212     208      2       0.0  
2     218     209     204     218     209     204      2       0.0  
3     222     213     208     222     213     208      2       0.0  
4     226     216     207     229     219     210      2       0.0  
5     226     216     206     227     217     207      2       0.0  
6     222     213     208     223     214     209      2       0.0  
7     226     218     216     227     219     217      2       1.0  
8     226     218     215     226     218     215      2       1.0  
9     220     215     211     220     215     211      2       1.0  

[10 rows x 307202 columns]

In [9]:
#Path and labels for Kevin
path = 'C:/Users/sam2146/Documents/522_Proj/Kevin/*.jpg'
label=[1,2,3]
df_k=flat_images(path,label[2])

In [10]:
position=[np.floor(i/7) for i in df_k.index]
df_k['position']=position

In [11]:
df_k.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  250  244  255  251  245  255  251  245  255  ...      85      91   
1  255  254  255  255  254  255  255  254  255  255  ...     199     187   
2  255  250  244  255  250  244  255  250  244  255  ...     169     164   
3  255  255  248  255  255  248  255  255  248  255  ...      94     106   
4  255  255  251  255  255  251  255  255  251  255  ...     160     164   
5  255  246  236  255  246  236  255  246  236  255  ...     211     203   
6  254  244  235  253  243  234  252  242  233  253  ...      97     104   
7  252  242  240  252  242  240  252  242  240  251  ...      97     111   
8  254  245  238  255  246  239  255  247  240  255  ...     158     151   
9  255  250  244  255  251  245  255  251  245  255  ...     134     134   

   307194  307195  307196  307197  307198  307199  label  position  
0      98      85      95     107      89     103      3       0.0  
1     210     198     186     210     198     186      3       0.0  
2     185     173     173     188     166     169      3       0.0  
3     103      97     111     105      97     112      3       0.0  
4     111     106     113      86      83      90      3       0.0  
5     239     225     222     227     207     206      3       0.0  
6      87      81      95      85      81      96      3       0.0  
7     106     100     114     104      98     110      3       1.0  
8     199     192     184     226     223     214      3       1.0  
9     123     111     115     116      97     103      3       1.0  

[10 rows x 307202 columns]

In [12]:
#concatenate all of the pictures into a single dataframe
big_df=pd.concat([df,df_t,df_k])
big_df.head()

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  254  255  255  254  255  255  254  255  255  ...     207     201   
1  223  213  204  225  215  206  225  215  206  224  ...      82      94   
2  223  213  204  222  212  203  221  211  202  222  ...      65      77   
3  223  213  204  223  213  204  224  214  205  225  ...      66      77   
4  218  208  198  222  212  202  223  213  203  223  ...      71      86   

   307194  307195  307196  307197  307198  307199  label  position  
0     213     208     202     213     208     202      1       0.0  
1      90      90     100      92      92     102      1       0.0  
2      63      65      77      63      65      77      1       0.0  
3      60      58      71      60      58      72      1       0.0  
4      75      74      92      73      72      90      1       0.0  

[5 rows x 307202 columns]

In [13]:
big_df.shape

(168, 307202)

### PCA reduction on the Data Frame

In [14]:
#Drop the label and position column to run the pca
nonlabel=big_df.drop(['label','position'],axis=1)
labels=big_df[['label','position']]

In [15]:
#PCA on the unlabeled dataframe
pca=PCA()
pca.fit(nonlabel)
csum=np.cumsum(pca.explained_variance_ratio_)
d=np.argmax(csum>=.9999)+1
d

162

In [16]:
#New dataframe shape
pca=PCA(n_components=d)
big_df_reduced=pca.fit_transform(nonlabel)
big_df.shape, big_df_reduced.shape

((168, 307202), (168, 162))

In [17]:
#adding the labels back to the reduced dataframe
pca_flat=pd.DataFrame(big_df_reduced)
pca_flat['label']=labels.label.values
pca_flat['position'] = labels.position.values
pca_flat.head()

0             1            2            3             4  \
0    441.932661   7952.285956 -6597.443229  4630.249901  13140.750464   
1   8989.608558  11673.484953  1131.446362  1844.040323  -8753.324088   
2  10668.507770  12591.264090   986.757039  5048.943308  -8241.432345   
3  11714.634149  12304.238553  1232.151830  6968.885752  -7723.520810   
4  12292.692526  11911.251073   987.619597  8391.517959  -6527.802073   

              5             6            7            8            9  ...  \
0  12722.120890  11494.439900 -8702.121877 -9162.197450 -1529.562493  ...   
1   1742.046292  -5237.215777  3268.983367 -2904.885423  3275.452421  ...   
2    693.392980  -2488.998214  1838.418512   125.335751  4046.357927  ...   
3    230.108391   -448.051474   390.515751  2478.778945  3187.198572  ...   
4   -187.887713    663.867692  -347.012928  3296.444577  2373.739414  ...   

        154        155       156       157        158        159        160  \
0 -5.406816  -0.271236 -3.931996  0.467108   0.837577  -0.563901  -0.942227   
1  2.564581  -1.487472  0.601396  0.160433  -5.907654  -1.736275  -1.412627   
2 -0.353201  -2.309761  3.313154 -0.944603   1.756764 -10.075806  -4.374063   
3  3.839871  -1.356766 -2.746948 -2.019972 -10.868602   1.781758  -0.310839   
4 -3.333900 -10.156313  2.697583  6.331006  -2.525387   0.411994  19.349089   

        161  label  position  
0  0.168963      1       0.0  
1 -1.312221      1       0.0  
2  2.741708      1       0.0  
3 -0.880320      1       0.0  
4 -2.866200      1       0.0  

[5 rows x 164 columns]

### Saving and reading in the data

In [18]:
#saving the dataframe to not have to rerun all the above code everytime
save_csv=pca_flat.to_csv(r'C:/Users/sam2146/Documents/522_Proj/small/pca_selfies.csv')

In [2]:
#reading in the saved dataframe
pca_flat=pd.read_csv(r'C:/Users/sam2146/Documents/522_Proj/small/pca_selfies.csv')
pca_flat.head()

Unnamed: 0             0             1            2            3  \
0           0    441.932661   7952.285956 -6597.443229  4630.249901   
1           1   8989.608558  11673.484953  1131.446362  1844.040323   
2           2  10668.507770  12591.264090   986.757039  5048.943308   
3           3  11714.634149  12304.238553  1232.151830  6968.885752   
4           4  12292.692526  11911.251073   987.619597  8391.517959   

              4             5             6            7            8  ...  \
0  13140.750464  12722.120890  11494.439900 -8702.121877 -9162.197450  ...   
1  -8753.324088   1742.046292  -5237.215777  3268.983367 -2904.885423  ...   
2  -8241.432345    693.392980  -2488.998214  1838.418512   125.335751  ...   
3  -7723.520810    230.108391   -448.051474   390.515751  2478.778945  ...   
4  -6527.802073   -187.887713    663.867692  -347.012928  3296.444577  ...   

        154        155       156       157        158        159        160  \
0 -5.406816  -0.271236 -3.931996  0.467108   0.837577  -0.563901  -0.942227   
1  2.564581  -1.487472  0.601396  0.160433  -5.907654  -1.736275  -1.412627   
2 -0.353201  -2.309761  3.313154 -0.944603   1.756764 -10.075806  -4.374063   
3  3.839871  -1.356766 -2.746948 -2.019972 -10.868602   1.781758  -0.310839   
4 -3.333900 -10.156313  2.697583  6.331006  -2.525387   0.411994  19.349089   

        161  label  position  
0  0.168963      1       0.0  
1 -1.312221      1       0.0  
2  2.741708      1       0.0  
3 -0.880320      1       0.0  
4 -2.866200      1       0.0  

[5 rows x 165 columns]

## MLP Classifier

### Scaling

In [20]:
#Scaling the data
X=pca_flat.drop(['position','label'],axis=1)
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [21]:
#creating a train test split
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [22]:
#X shapes
print(X_train.shape)
print(X_test.shape)

(120, 163)
(48, 163)


### Gridsearch

In [23]:
#Gridsearch for the MLP Classifer
params={'max_iter':[500],'alpha':[.00001,.001,1],'hidden_layer_sizes':[(100,100,100),(10,10,10)],'random_state':[42]}
grid=GridSearchCV(MLPClassifier(),params,refit=True,verbose=3,cv=5)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.375, total=   0.3s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.375, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s


[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.4583333333333333, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.4583333333333333, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.25, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.2916666666666667, total=   0.3s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.16666666666666666, total=   0.2s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:   11.9s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_iter': [500], 'alpha': [1e-05, 0.001, 1], 'hidden_layer_sizes': [(100, 100, 100), (10, 10, 10)], 'random_state': [42]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [24]:
#Use the test data to get predictions
y_pred=grid.predict(X_test)

### Results

In [25]:
print(accuracy_score(y_test, y_pred))

0.7708333333333334


In [26]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[16  0  0]
 [ 4  5  7]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       0.80      1.00      0.89        16
           2       1.00      0.31      0.48        16
           3       0.70      1.00      0.82        16

   micro avg       0.77      0.77      0.77        48
   macro avg       0.83      0.77      0.73        48
weighted avg       0.83      0.77      0.73        48



### running the gridsearch without scaling the data

In [82]:
#testing agian with the unscaled data
X=pca_flat.drop(['position','label'],axis=1)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [83]:
#Gridsearch
params={'max_iter':[500],'alpha':[.00001,.001,1],'hidden_layer_sizes':[(100,100,100),(10,10,10)],'random_state':[42]}
grid_ns=GridSearchCV(MLPClassifier(),params,refit=True,verbose=3,cv=5)
grid_ns.fit(X_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9166666666666666, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.625, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.6666666666666666, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.7083333333333334, total=   0.2s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=5

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:   10.2s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_iter': [500], 'alpha': [1e-05, 0.001, 1], 'hidden_layer_sizes': [(100, 100, 100), (10, 10, 10)], 'random_state': [42]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [84]:
y_pred=grid_ns.predict(X_test)

### Results

In [30]:
print(accuracy_score(y_test, y_pred))

0.9791666666666666


In [31]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[15  0  1]
 [ 0 16  0]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        16
           3       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



## SVM Classifier

### Unscaled SVM

In [32]:
param_grid = {'C': [1, 10,100], 'gamma': [1,0.1,0.001], 'kernel': ['rbf']} 
grid_rbf = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_rbf.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV] 

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=10, gamma=0.001, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV]  C=100, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV]  C=100, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV]  C=100, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV]  C=100, gamma=0.1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=100, gamma=0.001, kernel=rbf ...........

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    0.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1, 10, 100], 'gamma': [1, 0.1, 0.001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

### Results

In [33]:
#Best grid score
grid_rbf.best_score_

0.3333333333333333

In [34]:
pred_rbf = grid_rbf.predict(X_test)
print(confusion_matrix(y_test,pred_rbf))
print(classification_report(y_test,pred_rbf))

[[ 0  0 16]
 [ 0  0 16]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        16
           2       0.00      0.00      0.00        16
           3       0.33      1.00      0.50        16

   micro avg       0.33      0.33      0.33        48
   macro avg       0.11      0.33      0.17        48
weighted avg       0.11      0.33      0.17        48



### Scaled SVM

In [35]:
scaler = StandardScaler()
X=pca_flat.drop(['position','label'],axis=1)
X = scaler.fit_transform(X)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [36]:
param_grid = {'C': [1, 10,100], 'gamma': [1,0.1,0.001], 'kernel': ['rbf']} 
grid_rbf = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_rbf.fit(X_train_s,y_train_s)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.35714285714285715, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.3333333333333333, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.4523809523809524, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.38461538461538464, total=   0.0s
[CV] C=1, gamma=0.1, kernel=rbf ......................................
[CV]  C=1, gamma=0.1, kernel=rbf, score=0.358974358974359, total=   0.0s
[CV] C=1, gamma=0.001, kernel=rbf ....................................
[CV]

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    0.1s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1, 10, 100], 'gamma': [1, 0.1, 0.001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [37]:
grid_rbf.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

### Results

In [38]:
grid_rbf.best_score_

0.8833333333333333

In [39]:
pred_rbf = grid_rbf.predict(X_test_s)
print(confusion_matrix(y_test_s,pred_rbf))
print(classification_report(y_test_s,pred_rbf))

[[16  0  0]
 [ 0 15  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      0.94      0.97        16
           3       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



### Improved Gridsearch

In [40]:
param_grid = {'C': [0.00001,0.0001,0.001,0.01,0.1,1], 'coef0': [0.0001,0.001,0.01,0.1,0.5,1,1.5,2,2.5,3,10], 'degree': [1,2,3,4,5,6,7,8,9,10], 'kernel': ['poly']}
grid_poly = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid_poly.fit(X_train_s,y_train_s)

Fitting 3 folds for each of 660 candidates, totalling 1980 fits
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=1, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.0001, degree=2, kernel=poly ....................
[CV]  C=1e-05, coef0=0.0001, degree=2, kernel=poly, score=0.38461

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  C=1e-05, coef0=0.001, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=1, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=2, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=2, kernel=poly, score=0.38461538461538464, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=3, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001, degree=3, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.001, degree=3, kernel=poly .....................
[CV]  C=1e-05, coef0=0.001

[CV]  C=1e-05, coef0=0.1, degree=3, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=4, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=4, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=5, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=5, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=0.1, degree=5, kernel=poly .......................
[CV]  C=1e-05, coef0=0.1, degree=5, kerne

[CV]  C=1e-05, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=1, degree=10, kernel=poly ........................
[CV]  C=1e-05, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=1, degree=10, kernel=poly ........................
[CV]  C=1e-05, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1e-05, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=1e-05, coef0=1.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=1e-05, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=1e-05, coef0=1.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=1.5, degree=1, kernel=poly .......................
[CV]  C=1e-05, coef0=1.5, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1e-05, coef0=1.5, degree=2, kernel=poly .......................
[CV]  C=1e-05, coef0=1.5, degree=2, kernel=poly, score=0.9

[CV]  C=1e-05, coef0=2.5, degree=5, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=5, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=5, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=6, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=6, kernel=poly, score=0.9285714285714286, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=6, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=6, kernel=poly, score=0.8461538461538461, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=6, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=6, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=7, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=7, kernel=poly, score=0.9047619047619048, total=   0.0s
[CV] C=1e-05, coef0=2.5, degree=7, kernel=poly .......................
[CV]  C=1e-05, coef0=2.5, degree=7, kern

[CV]  C=1e-05, coef0=10, degree=10, kernel=poly, score=0.6666666666666666, total=   0.0s
[CV] C=1e-05, coef0=10, degree=10, kernel=poly .......................
[CV]  C=1e-05, coef0=10, degree=10, kernel=poly, score=0.6923076923076923, total=   0.0s
[CV] C=0.0001, coef0=0.0001, degree=1, kernel=poly ...................
[CV]  C=0.0001, coef0=0.0001, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.0001, coef0=0.0001, degree=1, kernel=poly ...................
[CV]  C=0.0001, coef0=0.0001, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=0.0001, degree=1, kernel=poly ...................
[CV]  C=0.0001, coef0=0.0001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.0001, coef0=0.0001, degree=2, kernel=poly ...................
[CV]  C=0.0001, coef0=0.0001, degree=2, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.0001, coef0=0.0001, degree=2, kernel=poly ...................
[CV]  C=0.0001, coef0=0.0001, degree=2

[CV]  C=0.0001, coef0=0.01, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=5, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=6, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=6, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=6, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=7, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.0001, coef0=0.01, degree=7, kernel=poly .....................
[CV]  C=0.0001, coef0=0.01, 

[CV]  C=0.0001, coef0=1, degree=2, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.0001, coef0=1, degree=2, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=2, kernel=poly, score=0.9487179487179487, total=   0.0s
[CV] C=0.0001, coef0=1, degree=2, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=2, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.0001, coef0=1, degree=3, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=3, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.0001, coef0=1, degree=3, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=3, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.0001, coef0=1, degree=3, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=3, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.0001, coef0=1, degree=4, kernel=poly ........................
[CV]  C=0.0001, coef0=1, degree=4, kernel=poly

[CV]  C=0.0001, coef0=2, degree=7, kernel=poly, score=0.6923076923076923, total=   0.0s
[CV] C=0.0001, coef0=2, degree=7, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=7, kernel=poly, score=0.6923076923076923, total=   0.0s
[CV] C=0.0001, coef0=2, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=8, kernel=poly, score=0.5714285714285714, total=   0.0s
[CV] C=0.0001, coef0=2, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=8, kernel=poly, score=0.5384615384615384, total=   0.0s
[CV] C=0.0001, coef0=2, degree=8, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=8, kernel=poly, score=0.6153846153846154, total=   0.0s
[CV] C=0.0001, coef0=2, degree=9, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=9, kernel=poly, score=0.4523809523809524, total=   0.0s
[CV] C=0.0001, coef0=2, degree=9, kernel=poly ........................
[CV]  C=0.0001, coef0=2, degree=9, kernel=poly

[CV]  C=0.0001, coef0=10, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.0001, coef0=10, degree=1, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=10, degree=1, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.0001, coef0=10, degree=2, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=2, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=0.0001, coef0=10, degree=2, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=2, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.0001, coef0=10, degree=2, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=2, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.0001, coef0=10, degree=3, kernel=poly .......................
[CV]  C=0.0001, coef0=10, degree=3, kernel=poly, score=

[CV]  C=0.001, coef0=0.001, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=7, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=7, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=7, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=8, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=8, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, degree=8, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.001, coef0=0.001, degree=8, kernel=poly .....................
[CV]  C=0.001, coef0=0.001, 

[CV]  C=0.001, coef0=0.5, degree=3, kernel=poly, score=0.7692307692307693, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=3, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=3, kernel=poly, score=0.7692307692307693, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=4, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=4, kernel=poly, score=0.42857142857142855, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=4, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=4, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=4, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=4, kernel=poly, score=0.41025641025641024, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=5, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=5, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.001, coef0=0.5, degree=5, kernel=poly .......................
[CV]  C=0.001, coef0=0.5, degree=5, ke

[CV]  C=0.001, coef0=1.5, degree=7, kernel=poly, score=0.5, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=7, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=7, kernel=poly, score=0.38461538461538464, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=7, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=7, kernel=poly, score=0.5128205128205128, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=8, kernel=poly, score=0.47619047619047616, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=8, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=8, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=8, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.001, coef0=1.5, degree=9, kernel=poly .......................
[CV]  C=0.001, coef0=1.5, degree=9, kernel=poly, score=

[CV]  C=0.001, coef0=3, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.001, coef0=3, degree=1, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.001, coef0=3, degree=1, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.001, coef0=3, degree=2, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=2, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.001, coef0=3, degree=2, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=2, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.001, coef0=3, degree=2, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=2, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=0.001, coef0=3, degree=3, kernel=poly .........................
[CV]  C=0.001, coef0=3, degree=3, kernel=poly, score=0.952380952380

[CV]  C=0.01, coef0=0.0001, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=6, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=6, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=7, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=7, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=7, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.01, coef0=0.0001, degree=8, kernel=poly .....................
[CV]  C=0.01, coef0=0.0001, 

[CV]  C=0.01, coef0=0.1, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=2, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=2, kernel=poly, score=0.7857142857142857, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=2, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=2, kernel=poly, score=0.717948717948718, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=2, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=2, kernel=poly, score=0.717948717948718, total=   0.0s
[CV] C=0.01, coef0=0.1, degree=3, kernel=poly ........................
[CV]  C=0.01, coef0=0.1, degree=3, kernel=poly, score=0.3571428

[CV]  C=0.01, coef0=1, degree=5, kernel=poly, score=0.5897435897435898, total=   0.0s
[CV] C=0.01, coef0=1, degree=5, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=5, kernel=poly, score=0.6410256410256411, total=   0.0s
[CV] C=0.01, coef0=1, degree=6, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=6, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=1, degree=6, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=1, degree=6, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=1, degree=7, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=7, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=1, degree=7, kernel=poly ..........................
[CV]  C=0.01, coef0=1, degree=7, kernel=poly, score=0.3589

[CV]  C=0.01, coef0=2, degree=9, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2, degree=10, kernel=poly .........................
[CV]  C=0.01, coef0=2, degree=10, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.01, coef0=2.5, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=2.5, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.01, coef0=2.5, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=2.5, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.01, coef0=2.5, degree=1, kernel=poly ........................
[CV]  C=0.01, coef0=2.5, degree=1, kernel=poly, score=0.923076923076

[CV]  C=0.01, coef0=10, degree=3, kernel=poly, score=0.7692307692307693, total=   0.0s
[CV] C=0.01, coef0=10, degree=4, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=4, kernel=poly, score=0.8571428571428571, total=   0.0s
[CV] C=0.01, coef0=10, degree=4, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=4, kernel=poly, score=0.8205128205128205, total=   0.0s
[CV] C=0.01, coef0=10, degree=4, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=4, kernel=poly, score=0.7692307692307693, total=   0.0s
[CV] C=0.01, coef0=10, degree=5, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=5, kernel=poly, score=0.8095238095238095, total=   0.0s
[CV] C=0.01, coef0=10, degree=5, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=5, kernel=poly, score=0.7692307692307693, total=   0.0s
[CV] C=0.01, coef0=10, degree=5, kernel=poly .........................
[CV]  C=0.01, coef0=10, degree=5, kernel=poly, score

[CV]  C=0.1, coef0=0.001, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=9, kernel=poly .......................
[CV]  C=0.1, coef0=0.001, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=10, kernel=poly ......................
[CV]  C=0.1, coef0=0.001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=10, kernel=poly ......................
[CV]  C=0.1, coef0=0.001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.001, degree=10, kernel=poly ......................
[CV]  C=0.1, coef0=0.001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.01, degree=1, kernel=poly ........................
[CV]  C=0.1, coef0=0.01, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.1, coef0=0.01, degree=1, kernel=poly ........................
[CV]  C=0.1, coef0=0.01, degree=1, kernel=poly, score

[CV]  C=0.1, coef0=0.5, degree=6, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=6, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=6, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=7, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=7, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=7, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=7, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=7, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=0.5, degree=8, kernel=poly .........................
[CV]  C=0.1, coef0=0.5, degree=8, kernel=poly, scor

[CV]  C=0.1, coef0=1.5, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=1.5, degree=10, kernel=poly ........................
[CV]  C=0.1, coef0=1.5, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=0.1, coef0=2, degree=1, kernel=poly ...........................
[CV] . C=0.1, coef0=2, degree=1, kernel=poly, score=1.0, total=   0.0s
[CV] C=0.1, coef0=2, degree=1, kernel=poly ...........................
[CV]  C=0.1, coef0=2, degree=1, kernel=poly, score=0.8717948717948718, total=   0.0s
[CV] C=0.1, coef0=2, degree=1, kernel=poly ...........................
[CV]  C=0.1, coef0=2, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=0.1, coef0=2, degree=2, kernel=poly ...........................
[CV]  C=0.1, coef0=2, degree=2, kernel=poly, score=0.9523809523809523, total=   0.0s
[CV] C=0.1, coef0=2, degree=2, kernel=poly ...........................
[CV]  C=0.1, coef0=2, degree=2, kernel=poly, score=0.9230769230769231, t

[CV]  C=0.1, coef0=3, degree=5, kernel=poly, score=0.5238095238095238, total=   0.0s
[CV] C=0.1, coef0=3, degree=5, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=5, kernel=poly, score=0.4358974358974359, total=   0.0s
[CV] C=0.1, coef0=3, degree=5, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=5, kernel=poly, score=0.5641025641025641, total=   0.0s
[CV] C=0.1, coef0=3, degree=6, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=6, kernel=poly, score=0.4523809523809524, total=   0.0s
[CV] C=0.1, coef0=3, degree=6, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=6, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=0.1, coef0=3, degree=6, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=6, kernel=poly, score=0.41025641025641024, total=   0.0s
[CV] C=0.1, coef0=3, degree=7, kernel=poly ...........................
[CV]  C=0.1, coef0=3, degree=7, kernel=poly, score=0.38095238095

[CV]  C=1, coef0=0.0001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.0001, degree=10, kernel=poly .......................
[CV]  C=1, coef0=0.0001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.0001, degree=10, kernel=poly .......................
[CV]  C=1, coef0=0.0001, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.001, degree=1, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=1, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=1, coef0=0.001, degree=1, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1, coef0=0.001, degree=1, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=1, kernel=poly, score=0.8974358974358975, total=   0.0s
[CV] C=1, coef0=0.001, degree=2, kernel=poly .........................
[CV]  C=1, coef0=0.001, degree=2, kernel=poly,

[CV]  C=1, coef0=0.1, degree=5, kernel=poly, score=0.35714285714285715, total=   0.0s
[CV] C=1, coef0=0.1, degree=5, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=5, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=5, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=6, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=0.1, degree=7, kernel=poly ...........................
[CV]  C=1, coef0=0.1, degree=7, kernel=poly, score=0.3333333333

[CV]  C=1, coef0=1, degree=9, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=10, kernel=poly ............................
[CV]  C=1, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=10, kernel=poly ............................
[CV]  C=1, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1, degree=10, kernel=poly ............................
[CV]  C=1, coef0=1, degree=10, kernel=poly, score=0.3333333333333333, total=   0.0s
[CV] C=1, coef0=1.5, degree=1, kernel=poly ...........................
[CV]  C=1, coef0=1.5, degree=1, kernel=poly, score=0.9761904761904762, total=   0.0s
[CV] C=1, coef0=1.5, degree=1, kernel=poly ...........................
[CV]  C=1, coef0=1.5, degree=1, kernel=poly, score=0.9230769230769231, total=   0.0s
[CV] C=1, coef0=1.5, degree=1, kernel=poly ...........................
[CV]  C=1, coef0=1.5, degree=1, kernel=poly, score=0.8974358974358975

[CV]  C=1, coef0=2.5, degree=4, kernel=poly, score=0.5384615384615384, total=   0.0s
[CV] C=1, coef0=2.5, degree=4, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=4, kernel=poly, score=0.6410256410256411, total=   0.0s
[CV] C=1, coef0=2.5, degree=5, kernel=poly ...........................
[CV] . C=1, coef0=2.5, degree=5, kernel=poly, score=0.5, total=   0.0s
[CV] C=1, coef0=2.5, degree=5, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=5, kernel=poly, score=0.358974358974359, total=   0.0s
[CV] C=1, coef0=2.5, degree=5, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=5, kernel=poly, score=0.4358974358974359, total=   0.0s
[CV] C=1, coef0=2.5, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=6, kernel=poly, score=0.38095238095238093, total=   0.0s
[CV] C=1, coef0=2.5, degree=6, kernel=poly ...........................
[CV]  C=1, coef0=2.5, degree=6, kernel=poly, score=0.358974358974359, total=  

[CV]  C=1, coef0=10, degree=10, kernel=poly, score=0.6666666666666666, total=   0.0s
[CV] C=1, coef0=10, degree=10, kernel=poly ...........................
[CV]  C=1, coef0=10, degree=10, kernel=poly, score=0.6923076923076923, total=   0.0s


[Parallel(n_jobs=1)]: Done 1980 out of 1980 | elapsed:   10.1s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1], 'coef0': [0.0001, 0.001, 0.01, 0.1, 0.5, 1, 1.5, 2, 2.5, 3, 10], 'degree': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'kernel': ['poly']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [41]:
grid_poly.best_params_

{'C': 1e-05, 'coef0': 1, 'degree': 2, 'kernel': 'poly'}

### Results

In [42]:
grid_poly.best_score_

0.9416666666666667

In [43]:
from sklearn.metrics import classification_report,confusion_matrix
pred_poly = grid_poly.predict(X_test_s)
print(confusion_matrix(y_test_s,pred_poly))
print(classification_report(y_test_s,pred_poly))

[[15  1  0]
 [ 0 16  0]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        16
           3       1.00      1.00      1.00        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



## Random Forrest

### Random Forrest with unscaled data

In [3]:
X=pca_flat.drop(['position','label'],axis=1)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [4]:
#simple model using the defaults
rf = RandomForestClassifier(random_state=101)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

### Results

In [5]:
print(accuracy_score(y_test, y_pred_rf))

1.0


In [6]:
print(classification_report(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        16

   micro avg       1.00      1.00      1.00        48
   macro avg       1.00      1.00      1.00        48
weighted avg       1.00      1.00      1.00        48

[[16  0  0]
 [ 0 16  0]
 [ 0  0 16]]


When Kevin initially ran this model on his computer he got 98% and used the gridsearch to improve it to 100%. We werent sure why running it on this computer gave us different results.

### Random Forrest with a gridsearch

In [48]:
param_grid = {'n_estimators': [10, 25, 50, 100], 
              'max_depth': [10, 15, 30, 50],
              'min_samples_split':[2, 10, 50, 100], 
              'min_impurity_decrease': [.0000001, .00001, .001, .1]} 

In [49]:
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)

Fitting 3 folds for each of 256 candidates, totalling 768 fits
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10, score=0.6190476190476191, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10, score=0.9487179487179487, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=10, score=0.9230769230769231, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=25 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=25, score=0.9523809523809523, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=25 

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=50, score=0.9743589743589743, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=50 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=10, n_est

[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10, score=0.8809523809523809, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10, score=0.9230769230769231, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=10, score=0.9230769230769231, total=   0.0s
[CV] max_dep

[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=50 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.

[CV]  max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50 
[CV]  max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50 
[CV]  max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s

[CV]  max_depth=10, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=100, score=0.9743589743589743, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=100 
[CV]  max_depth=10, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=100, score=0.9743589743589743, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10 
[CV]  max_depth=10, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=10, mi

[CV]  max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100, score=0.9487179487179487, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100, score=0.8461538461538461, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10 
[CV]  max_depth=15, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=15, min_impurity_de

[CV]  max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=10, score=0.5897435897435898, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25 
[CV]  max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25, score=0.6666666666666666, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25 
[CV]  max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25, score=0.8974358974358975, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25 
[CV]  max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=25, score=0.9487179487179487, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=50 
[CV]  max_depth=15, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=15, min_impu

[CV]  max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=50 
[CV]  max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100 
[CV]  max_depth=15, min_impurity_decrease=0.001, min_samples_split=10, n_estimators=100, score=0.9743589743589743, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.001, min_samples_split=

[CV]  max_depth=15, min_impurity_decrease=0.1, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10 
[CV]  max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10, score=0.9523809523809523, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10 
[CV]  max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10, score=0.6666666666666666, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10 
[CV]  max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=10, score=0.6923076923076923, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=25 
[CV]  max_depth=15, min_impurity_decrease=0.1, min_samples_split=10, n_estimators=25, score=1.0, total=   0.0s
[CV] max_depth=15, min_impurity_decrease=0.1, min_samples_sp

[CV]  max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=1e-07, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-07, min_samples_split=10, n_estimators=10 
[CV]  max_depth=30, min_impurity_decrease=1e-07, min_samples_split=10, n_estimators=10, score=0.8809523809523809, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-07, min_samples_split=10, n_e

[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=25, score=0.8717948717948718, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50 
[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50 
[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50 
[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=50, score=0.9743589743589743, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=2, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_spli

[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=1e-05, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10, score=0.9761904761904762, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10, score=0.7435897435897436, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=2, n_estimators=10, score=0.9487179487179487, total=   0.0s
[CV] max_dep

[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=0.001, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.1, min_samples_split=2, n_estimators=10 
[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=2, n_estimators=10, score=0.7857142857142857, total=   0.0s
[CV] 

[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=50 
[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=50 
[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=50, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=100 
[CV]  max_depth=30, min_impurity_decrease=0.1, min_samples_split=100, n_estimators=100, score=0.3333333333333333, total=   0.0s
[CV] max_depth=30

[CV]  max_depth=50, min_impurity_decrease=1e-07, min_samples_split=50, n_estimators=100, score=0.8717948717948718, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10 
[CV]  max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10 
[CV]  max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10 
[CV]  max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=10, score=0.3333333333333333, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=25 
[CV]  max_depth=50, min_impurity_decrease=1e-07, min_samples_split=100, n_estimators=25, score=0.3333333333333333, total=   0.0s
[CV

[CV]  max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=50, score=0.9487179487179487, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=50 
[CV]  max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=50, score=0.9230769230769231, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100, score=1.0, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=1e-05, min_samples_split=50, n_estimators=100, score=0.8974358974358975, total=   0.0s
[CV] max_depth=50, min_impurity_decr

[CV]  max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=50, score=1.0, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=50 
[CV]  max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=50, score=0.9487179487179487, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100, score=0.7619047619047619, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100, score=0.8974358974358975, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100 
[CV]  max_depth=50, min_impurity_decrease=0.001, min_samples_split=50, n_estimators=100, score=0.8974358974358975, total=   0.0s
[CV] max_depth=50, mi

[CV]  max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=10, score=0.717948717948718, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25 
[CV]  max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25, score=0.7380952380952381, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25 
[CV]  max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25, score=1.0, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25 
[CV]  max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=25, score=0.6666666666666666, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=50 
[CV]  max_depth=50, min_impurity_decrease=0.1, min_samples_split=50, n_estimators=50, score=0.7857142857142857, total=   0.0s
[CV] max_depth=50, min_impurity_decrease=0.1, 

[Parallel(n_jobs=1)]: Done 768 out of 768 | elapsed:   30.3s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [10, 25, 50, 100], 'max_depth': [10, 15, 30, 50], 'min_samples_split': [2, 10, 50, 100], 'min_impurity_decrease': [1e-07, 1e-05, 0.001, 0.1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [50]:
#best parameters
print(grid.best_params_)
print(grid.best_estimator_)

{'max_depth': 10, 'min_impurity_decrease': 1e-07, 'min_samples_split': 2, 'n_estimators': 100}
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=1e-07, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


### Results

In [51]:
grid_predictions = grid.predict(X_test)
print(accuracy_score(y_test, grid_predictions))

1.0


In [52]:
print(classification_report(y_test,grid_predictions))
print(confusion_matrix(y_test, grid_predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        16

   micro avg       1.00      1.00      1.00        48
   macro avg       1.00      1.00      1.00        48
weighted avg       1.00      1.00      1.00        48

[[16  0  0]
 [ 0 16  0]
 [ 0  0 16]]


## Testing with pets, classmates, and celebrities

In [92]:
names=['Channing Tatum','Brad Pitt','Jennifer Lawrence','Random Lady','George Clooney','Sadie','Bella','Dakota','Hunter','Buster','Hawk','Joe','Daniel','Nathan','Morgan','Dr. Lammers']

In [53]:
def flat_images(path,label):
#this function reads in images and then flattens them into a dataframe
    images=imread_collection(path)
    flat_images=[]
    for i in range(len(images)):
        img=images[i]
        img1=img.flatten()
        flat_images.append(img1)
    length=flat_images[1].shape
    df=pd.DataFrame(flat_images)
    df['label']=label
    return(df)

In [86]:
path = 'C:/Users/sam2146/Documents/522_Proj/test_pics/*.jpg'
label=[4]
test=flat_images(path,label[0])
test.head()

0    1    2    3    4    5    6    7    8    9  ...  307191  307192  \
0   42   42   50   43   43   51   45   45   53   44  ...     122     131   
1  110  136  137  102  128  129  112  137  141  111  ...     141     145   
2  110  112  111  106  108  107  113  115  114  121  ...      44      30   
3  157  153  124  157  153  124  156  152  123  159  ...     179     187   
4   70   80   79   72   82   81   71   81   80   77  ...     150     157   

   307193  307194  307195  307196  307197  307198  307199  label  
0     126     119     128     123     118     127     122      4  
1     122     138     142     119     134     138     115      4  
2      30      49      37      37      49      37      39      4  
3     166     181     189     168     171     178     160      4  
4     139     150     157     139     152     159     141      4  

[5 rows x 307201 columns]

In [55]:
save_csv=test.to_csv(r'C:/Users/sam2146/Documents/522_Proj/test_pics/test.csv')
test=pd.read_csv(r'C:/Users/sam2146/Documents/522_Proj/test_pics/test.csv')
test.head()

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  307191  \
0           0   42   42   50   43   43   51   45   45   53  ...     122   
1           1  110  136  137  102  128  129  112  137  141  ...     141   
2           2  185  177  156  191  183  162  184  176  155  ...     141   
3           3  110  112  111  106  108  107  113  115  114  ...      44   
4           4  157  153  124  157  153  124  156  152  123  ...     179   

   307192  307193  307194  307195  307196  307197  307198  307199  label  
0     131     126     119     128     123     118     127     122      4  
1     145     122     138     142     119     134     138     115      4  
2     114      87     147     120      93     144     117      88      4  
3      30      30      49      37      37      49      37      39      4  
4     187     166     181     189     168     171     178     160      4  

[5 rows x 307202 columns]

In [89]:
nolabel=test.drop(['label'],axis=1)

In [90]:
test_reduced=pca.transform(nolabel)
test.shape, test_reduced.shape

((16, 307201), (16, 162))

In [91]:
test_reduced=pd.DataFrame(test_reduced)
test_reduced['lab']=test.label.values

### Predictions for each model

#### Random Forrest

In [96]:
results=grid.predict(test_reduced)
dict(zip(names,results))

{'Channing Tatum': 1,
 'Brad Pitt': 1,
 'Jennifer Lawrence': 1,
 'Random Lady': 1,
 'George Clooney': 1,
 'Sadie': 1,
 'Bella': 1,
 'Dakota': 1,
 'Hunter': 1,
 'Buster': 1,
 'Hawk': 2,
 'Joe': 2,
 'Daniel': 2,
 'Nathan': 1,
 'Morgan': 1,
 'Dr. Lammers': 3}

#### Simple Vector Machine

In [97]:
scaler.transform(test_reduced)
results=grid_poly.predict(test_reduced)
dict(zip(names,results))

{'Channing Tatum': 1,
 'Brad Pitt': 1,
 'Jennifer Lawrence': 1,
 'Random Lady': 1,
 'George Clooney': 1,
 'Sadie': 3,
 'Bella': 1,
 'Dakota': 1,
 'Hunter': 1,
 'Buster': 1,
 'Hawk': 3,
 'Joe': 1,
 'Daniel': 1,
 'Nathan': 1,
 'Morgan': 1,
 'Dr. Lammers': 3}

#### MLP Classifier

In [108]:
results=grid_ns.predict(test_reduced)
dict(zip(names,results))

{'Channing Tatum': 1,
 'Brad Pitt': 1,
 'Jennifer Lawrence': 1,
 'Random Lady': 1,
 'George Clooney': 1,
 'Sadie': 2,
 'Bella': 1,
 'Dakota': 2,
 'Hunter': 1,
 'Buster': 1,
 'Hawk': 2,
 'Joe': 2,
 'Daniel': 2,
 'Nathan': 1,
 'Morgan': 1,
 'Dr. Lammers': 2}

### Voting Classifier to see how the test images are grouped

In [103]:
mlp_clf=MLPClassifier()
svm_clf=SVC()
rfc_clf=RandomForestClassifier()


voting_clf = VotingClassifier(
    estimators=[('mlp', mlp_clf), ('svm', svm_clf), ('rfc', rfc_clf)],
    voting='hard')
voting_clf.fit(X_train, y_train)

for clf in (mlp_clf, svm_clf, rfc_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

MLPClassifier 0.8125
SVC 0.3333333333333333
RandomForestClassifier 1.0
VotingClassifier 0.9583333333333334


In [104]:
results=clf.predict(test_reduced)
dict(zip(names,results))

{'Channing Tatum': 1,
 'Brad Pitt': 1,
 'Jennifer Lawrence': 1,
 'Random Lady': 1,
 'George Clooney': 1,
 'Sadie': 1,
 'Bella': 1,
 'Dakota': 1,
 'Hunter': 1,
 'Buster': 1,
 'Hawk': 3,
 'Joe': 1,
 'Daniel': 3,
 'Nathan': 1,
 'Morgan': 1,
 'Dr. Lammers': 1}