# Combined CSV #

In [1]:
from skimage.io import imread_collection
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
def flat_images(path,label):
    images=imread_collection(path)
    flat_images=[]
    for i in range(len(images)):
        img=images[i]
        img1=img.flatten()
        flat_images.append(img1)
    length=flat_images[1].shape
    df=pd.DataFrame(flat_images)
    df['label']=label
    return(df)

In [3]:
path = 'C:/Users/sam2146/Documents/522_Proj/small/*.jpg'
label=[1,2,3]
df=flat_images(path,label[0])

In [4]:
position=[np.floor(i/7) for i in df.index]
df['position']=position

In [5]:
df.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  254  255  255  254  255  255  254  255  255  ...     207     201   
1  223  213  204  225  215  206  225  215  206  224  ...      82      94   
2  223  213  204  222  212  203  221  211  202  222  ...      65      77   
3  223  213  204  223  213  204  224  214  205  225  ...      66      77   
4  218  208  198  222  212  202  223  213  203  223  ...      71      86   
5  219  209  200  222  212  203  226  216  207  225  ...      71      79   
6  219  206  197  223  210  201  222  209  200  220  ...      59      74   
7  225  216  207  225  216  207  225  216  207  224  ...      40      51   
8  223  214  209  223  214  209  224  215  210  222  ...     228     226   
9  221  212  205  221  212  205  223  214  207  223  ...     229     226   

   307194  307195  307196  307197  307198  307199  label  position  
0     213     208     202     213     208     202      1       0.0  
1      90      90     100      92      92     102      1       0.0  
2      63      65      77      63      65      77      1       0.0  
3      60      58      71      60      58      72      1       0.0  
4      75      74      92      73      72      90      1       0.0  
5      73      71      85      76      73      94      1       0.0  
6      49      52      69      65      68      87      1       0.0  
7      37      35      46      38      36      47      1       1.0  
8     236     228     226     236     228     226      1       1.0  
9     237     229     226     238     230     227      1       1.0  

[10 rows x 307202 columns]

In [6]:
path = 'C:/Users/sam2146/Documents/522_Proj/Tyler/*.jpg'
label=[1,2,3]
df_t=flat_images(path,label[1])

In [7]:
position=[np.floor(i/7) for i in df_t.index]
df_t['position']=position

In [8]:
df_t.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  246  241  235  248  243  237  250  245  239  250  ...     215     212   
1  255  253  246  255  253  246  255  253  246  255  ...     215     211   
2  243  233  231  243  233  231  243  233  231  244  ...     209     204   
3  243  233  231  244  234  232  244  234  232  244  ...     212     207   
4  248  238  229  249  239  230  250  240  231  249  ...     215     206   
5  248  238  229  249  239  230  249  239  230  247  ...     216     206   
6  243  234  229  243  234  229  243  234  229  243  ...     211     206   
7  251  243  240  251  243  240  251  243  240  251  ...     217     214   
8  247  238  231  248  239  232  248  239  232  247  ...     218     215   
9  252  245  239  250  243  237  250  243  237  252  ...     215     211   

   307194  307195  307196  307197  307198  307199  label  position  
0     223     215     212     225     217     214      2       0.0  
1     223     212     208     223     212     208      2       0.0  
2     218     209     204     218     209     204      2       0.0  
3     222     213     208     222     213     208      2       0.0  
4     226     216     207     229     219     210      2       0.0  
5     226     216     206     227     217     207      2       0.0  
6     222     213     208     223     214     209      2       0.0  
7     226     218     216     227     219     217      2       1.0  
8     226     218     215     226     218     215      2       1.0  
9     220     215     211     220     215     211      2       1.0  

[10 rows x 307202 columns]

In [9]:
path = 'C:/Users/sam2146/Documents/522_Proj/Kevin/*.jpg'
label=[1,2,3]
df_k=flat_images(path,label[2])

In [10]:
position=[np.floor(i/7) for i in df_k.index]
df_k['position']=position

In [11]:
df_k.head(10)

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  250  244  255  251  245  255  251  245  255  ...      85      91   
1  255  254  255  255  254  255  255  254  255  255  ...     199     187   
2  255  250  244  255  250  244  255  250  244  255  ...     169     164   
3  255  255  248  255  255  248  255  255  248  255  ...      94     106   
4  255  255  251  255  255  251  255  255  251  255  ...     160     164   
5  255  246  236  255  246  236  255  246  236  255  ...     211     203   
6  254  244  235  253  243  234  252  242  233  253  ...      97     104   
7  252  242  240  252  242  240  252  242  240  251  ...      97     111   
8  254  245  238  255  246  239  255  247  240  255  ...     158     151   
9  255  250  244  255  251  245  255  251  245  255  ...     134     134   

   307194  307195  307196  307197  307198  307199  label  position  
0      98      85      95     107      89     103      3       0.0  
1     210     198     186     210     198     186      3       0.0  
2     185     173     173     188     166     169      3       0.0  
3     103      97     111     105      97     112      3       0.0  
4     111     106     113      86      83      90      3       0.0  
5     239     225     222     227     207     206      3       0.0  
6      87      81      95      85      81      96      3       0.0  
7     106     100     114     104      98     110      3       1.0  
8     199     192     184     226     223     214      3       1.0  
9     123     111     115     116      97     103      3       1.0  

[10 rows x 307202 columns]

In [12]:
big_df=pd.concat([df,df_t,df_k])
big_df.head()

0    1    2    3    4    5    6    7    8    9  ...  307192  307193  \
0  255  254  255  255  254  255  255  254  255  255  ...     207     201   
1  223  213  204  225  215  206  225  215  206  224  ...      82      94   
2  223  213  204  222  212  203  221  211  202  222  ...      65      77   
3  223  213  204  223  213  204  224  214  205  225  ...      66      77   
4  218  208  198  222  212  202  223  213  203  223  ...      71      86   

   307194  307195  307196  307197  307198  307199  label  position  
0     213     208     202     213     208     202      1       0.0  
1      90      90     100      92      92     102      1       0.0  
2      63      65      77      63      65      77      1       0.0  
3      60      58      71      60      58      72      1       0.0  
4      75      74      92      73      72      90      1       0.0  

[5 rows x 307202 columns]

In [13]:
big_df.shape

(168, 307202)

In [14]:
nonlabel=big_df.drop(['label','position'],axis=1)
labels=big_df[['label','position']]


In [15]:
pca=PCA()
pca.fit(nonlabel)
csum=np.cumsum(pca.explained_variance_ratio_)
d=np.argmax(csum>=.9999)+1
d

162

In [16]:
pca=PCA(n_components=d)
big_df_reduced=pca.fit_transform(nonlabel)
big_df.shape, big_df_reduced.shape

((168, 307202), (168, 162))

In [46]:
pca_flat['label']=labels.label.values
pca_flat['position'] = labels.position.values
pca_flat.head()

0             1            2            3             4  \
0    441.932661   7952.285956 -6597.443229  4630.249901  13140.750464   
1   8989.608558  11673.484953  1131.446362  1844.040323  -8753.324088   
2  10668.507770  12591.264090   986.757039  5048.943308  -8241.432345   
3  11714.634149  12304.238553  1232.151830  6968.885752  -7723.520810   
4  12292.692526  11911.251073   987.619597  8391.517959  -6527.802073   

              5             6            7            8            9  ...  \
0  12722.120890  11494.439900 -8702.121877 -9162.197450 -1529.562493  ...   
1   1742.046292  -5237.215777  3268.983367 -2904.885423  3275.452421  ...   
2    693.392980  -2488.998214  1838.418512   125.335751  4046.357927  ...   
3    230.108391   -448.051474   390.515751  2478.778945  3187.198572  ...   
4   -187.887713    663.867692  -347.012928  3296.444577  2373.739414  ...   

        154        155       156       157        158        159        160  \
0 -5.406816  -0.271236 -3.931996  0.467108   0.837577  -0.563901  -0.942227   
1  2.564581  -1.487472  0.601396  0.160433  -5.907654  -1.736275  -1.412627   
2 -0.353201  -2.309761  3.313154 -0.944603   1.756764 -10.075806  -4.374063   
3  3.839871  -1.356766 -2.746948 -2.019972 -10.868602   1.781758  -0.310839   
4 -3.333900 -10.156313  2.697583  6.331006  -2.525387   0.411994  19.349089   

        161  position  label  
0  0.168963       0.0      1  
1 -1.312221       0.0      1  
2  2.741708       0.0      1  
3 -0.880320       0.0      1  
4 -2.866200       0.0      1  

[5 rows x 164 columns]

In [47]:
save_csv=pca_flat.to_csv(r'C:/Users/sam2146/Documents/522_Proj/small/pca_selfies.csv')

In [51]:
X=pca_flat.drop(['position','label'],axis=1)
y=pca_flat['label']
strat=pca_flat[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [53]:
print(X_train.shape)
print(X_test.shape)

(120, 162)
(48, 162)


In [2]:
df=pd.read_csv(r'C:/Users/sam2146/Documents/522_Proj/small/pca_selfies.csv')
df.head()

Unnamed: 0             0             1            2            3  \
0           0    441.932661   7952.285956 -6597.443229  4630.249901   
1           1   8989.608558  11673.484953  1131.446362  1844.040323   
2           2  10668.507770  12591.264090   986.757039  5048.943308   
3           3  11714.634149  12304.238553  1232.151830  6968.885752   
4           4  12292.692526  11911.251073   987.619597  8391.517959   

              4             5             6            7            8  ...  \
0  13140.750464  12722.120890  11494.439900 -8702.121877 -9162.197450  ...   
1  -8753.324088   1742.046292  -5237.215777  3268.983367 -2904.885423  ...   
2  -8241.432345    693.392980  -2488.998214  1838.418512   125.335751  ...   
3  -7723.520810    230.108391   -448.051474   390.515751  2478.778945  ...   
4  -6527.802073   -187.887713    663.867692  -347.012928  3296.444577  ...   

        154        155       156       157        158        159        160  \
0 -5.406816  -0.271236 -3.931996  0.467108   0.837577  -0.563901  -0.942227   
1  2.564581  -1.487472  0.601396  0.160433  -5.907654  -1.736275  -1.412627   
2 -0.353201  -2.309761  3.313154 -0.944603   1.756764 -10.075806  -4.374063   
3  3.839871  -1.356766 -2.746948 -2.019972 -10.868602   1.781758  -0.310839   
4 -3.333900 -10.156313  2.697583  6.331006  -2.525387   0.411994  19.349089   

        161  position  label  
0  0.168963       0.0      1  
1 -1.312221       0.0      1  
2  2.741708       0.0      1  
3 -0.880320       0.0      1  
4 -2.866200       0.0      1  

[5 rows x 165 columns]

In [19]:
X=df.drop(['position','label'],axis=1)
scaler=StandardScaler()
X=scaler.fit_transform(X)

C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [28]:
X=df.drop(['position','label'],axis=1)
y=df['label']
strat=df[['position','label']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.285,stratify=strat,random_state=100)

In [ ]:
mlp classifier, change number of layers

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [29]:
params={'max_iter':[500],'alpha':[.00001,.001,1],'hidden_layer_sizes':[(100,100,100),(10,10,10)],'random_state':[42]}
grid=GridSearchCV(MLPClassifier(),params,refit=True,verbose=3,cv=5)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  alpha=1e-05, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9166666666666666, total=   0.0s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.625, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.6666666666666666, total=   0.1s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.7083333333333334, total=   0.2s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.6666666666666666, total=   0.3s
[CV] alpha=1e-05, hidden_layer_sizes=(10, 10, 10), max_iter=500, ra

C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.5, total=   0.3s
[CV] alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 
[CV]  alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.8s
[CV] alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.9s
[CV] alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=1.0, total=   0.9s
[CV] alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9583333333333334, total=   0.8s
[CV] alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42 


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=1, hidden_layer_sizes=(100, 100, 100), max_iter=500, random_state=42, score=0.9166666666666666, total=   0.9s
[CV] alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.625, total=   0.1s
[CV] alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.6666666666666666, total=   0.4s
[CV] alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.75, total=   0.4s
[CV] alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.6666666666666666, total=   0.3s
[CV] alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42 
[CV]  alpha=1, hidden_layer_sizes=(10, 10, 10), max_iter=500, random_state=42, score=0.5416666666666666, total=   0.3s


C:\Users\sam2146\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:   10.3s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_iter': [500], 'alpha': [1e-05, 0.001, 1], 'hidden_layer_sizes': [(100, 100, 100), (10, 10, 10)], 'random_state': [42]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [30]:
y_pred=grid.predict(X_test)

In [31]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[15  0  1]
 [ 0 16  0]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        16
           3       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



In [48]:
sadie.shape

(1687500,)

In [19]:
sadie=io.imread('IMG_1790.jpg')
#plt.imshow(sadie)
sadie=sadie.flatten()
sadie=pd.DataFrame(sadie,columns=list(range(1687500)))
big_df_reduced=pca.transform(sadie)
big_df.shape, big_df_reduced.shape

ValueError: Shape of passed values is (1687500, 1), indices imply (1687500, 1687500)

In [18]:
#image_path='C:\Users\sam2146\Documents\522_Proj\IMG_1790.jpg'
from skimage import io
sadie=io.imread('IMG_1790.jpg')
#dog=grid.predict(sadie)

In [27]:
grid.best_params_

{'alpha': 1,
 'hidden_layer_sizes': (100, 100, 100),
 'max_iter': 500,
 'random_state': 42}

In [25]:
mlp=MLPClassifier(max_iter=500, alpha=.00001 ,random_state=42)
mlp.fit(X_train,y_train)
y_pred=mlp.predict(X_test)

In [32]:
accuracy_score(y_test, y_pred)

NameError: name 'accuracy_score' is not defined

In [31]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[15  0  1]
 [ 0 16  0]
 [ 0  0 16]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        16
           3       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        48
   macro avg       0.98      0.98      0.98        48
weighted avg       0.98      0.98      0.98        48



In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [.01,1,100], 'gamma': [ .01,1,100],'kernel': ['rbf']} 
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)
grid.fit(X_train,y_train)
grid_predictions = grid.predict(X_test)
grid.best_params_
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))